---
  - name: verrify ssh key doesnt exist
    delegate_to: localhost
    file:
      path: "{{ inventory_dir }}/ssh/.id_rsa"
      state: absent

  - name: verrify ssh key doesnt exist
    delegate_to: localhost
    file:
      path: "{{ inventory_dir }}/ssh/.id_rsa.pub"
      state: absent

  - name: generate SSH key
    command: ssh-keygen -b 2048 -t rsa -f "{{ inventory_dir }}/ssh/.id_rsa" -q -N ""
    delegate_to: localhost
