# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Author: Uri Zaidenwerg

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('hosts.yml')

#ssh_user = "zaiden"

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |server|
    config.vm.define server["name"] do |srv|
      srv.vm.box = server["box"]
      srv.vm.network "private_network", ip: server["ip"]
      srv.vm.hostname = server["name"]

#      srv.vm.synced_folder  "~/.ssh", "/root/.ssh", owner: ssh_user, group: ssh_user
      srv.vm.synced_folder  "~/.ssh", "/root/.ssh", owner: "root", group: "root"

      srv.vm.provider :virtualbox do |vb|
        vb.name = server["name"]
        vb.memory = server["ram"]
        vb.cpus = server["cpu"]
      end

#      srv.vm.provision "shell" do |ssh|
#        ssh_pub_key = $ssh_pub_key_sanjer
#        ssh.inline = <<-SHELL
#          mkdir -p /root/.ssh
#          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
#	       SHELL
#      end

    end
  end
end
