# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Author: Uri Zaidenwerg

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require modules
require 'yaml'
require 'set'

# Read YAML file with box details
hostfile = YAML.load_file('wishlist.yml')
nodeset = Set.new []

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hostfile.each do |group,objects| #T1:
    objects.each do |object,subobjects| #T2:
      if object == 'hosts' #T3:
        subobjects.each do |subobject,vars| #T4:
          unless nodeset.include?(subobject) #T5:
            nodeset.add(subobject)
            config.vm.define subobject do |nodeconf| #T6:
              nodeconf.vm.box = vars["box"]
              nodeconf.vm.network "private_network", ip: vars["ansible_host"].to_s
              nodeconf.vm.hostname = subobject
              nodeconf.vm.provider :virtualbox do |vb| #T7:
                vb.name = subobject
                vb.memory = vars["ram"]
                vb.cpus = vars["cpu"]
              end #End of T7
            end #End of T6
          end #End of T5
        end #End of T4
      elsif object == "vars"
        # This part should handle group vars
      end #End of T3
    end #End of T2
  end #End of T1

  config.vm.provision "ansible" do |ansible| #B1: Provision with ansible
    ansible.playbook = "./provisioning/arve.provision.yml"
  end #End B1
end #The End
