---
appservers:
  hosts:
    app01:
      box: centos/7
      ram: 256
      cpu: 1
      ip: 172.24.5.101
  vars:
    testing: value

webservers:
  hosts:
    web01:
      box: centos/7
      ram: 256
      cpu: 1
      ip: 172.24.5.111
    web02:
      box: centos/7
      ram: 256
      cpu: 1
      ip: 172.24.5.112

all:
  children:
    webservers:
    appservers:
  hosts:
    app01:
